### ISSUE TITLE
[Support] How to use with dependency injection?

### ISSUE THREAD

**Issue by span** [uipath-open/corewf#184]
Hi!

Thank you for this great effort. It will hopefully aid us in porting old framework code to net6.

In the "old" workflow foundation, it was possible to use unity and a dependency injection plugin [0] to inject services into the Activities.

Is it possible to use `CoreWF` with net6 dependency injection? If so, how can it be configured?

Cheers,
Daniel

[0] https://github.com/dimaKudr/Unity.WF

**Comment by dmetzgar** [comment]
I'm not sure if the project you linked will work with CoreWF as I haven't tested it.

There is a native way to do what you're describing in WF with activity extensions that will work in CoreWF: https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/using-activity-extensions

Activity extensions are not persisted so there's really no benefit over DI libraries. I would avoid adding a dependency to a DI library into System.Activities because we intend to keep the dependencies to a minimum. One could always add an extension for a DI container. But for something like constructor injection, DI won't work because the WF runtime needs to be in charge of activity object creation.

**Comment by span** [comment]
Thank you. Adding the `IServiceProvider` as an extension and then loading it from the code activity context works great. It has ben very helpful in porting our old solution.
