### ISSUE TITLE
please support maui for designer

### ISSUE THREAD

**Issue by juepiezhongren** [uipath-open/corewf#190]
said above.

**Comment by dmetzgar** [comment]
This is a way bigger ask than it sounds and has been brought up in previous issues (#45, #58, #59). The designer code is not part of this repo. The code for the rehostable WF designer is in the .NET Framework and is exposed via [referencesource](https://referencesource.microsoft.com/#System.Activities.Presentation). It's important to note that referencesource includes C# source code files but not XAML so that would have to be reverse-engineered. Then there's the work of actually porting all of that to run in MAUI. There's not enough benefit to justify the cost.
